apiVersion: v1
kind: Secret
metadata:
  name: gregory-bootstrap-secret
  namespace: greg01-b2y9g
  labels:
    vm-selector: gregory-secret
stringData:
  gregory-passwd: |-
    $1$FWGBR9jI$vatdW5FRyG.42BTnLsxFu.
